t=int(input())
while(t):
    n,k,p=map(int,input().split())
    l=list(map(int,input().split()))
    if(p==0):
        sel=max(l)
        key=0
    else:
        sel=min(l)
        key=1
    k-=1
    if(k<1000):
        while(k):
            if(key==0):
                r=l.index(sel)
                sel1=sel
                if(r==0):
                    s1=1000000000
                else:
                    s1=l[r-1]
                if(r==n-1):
                    s2=1000000000
                else:
                    s2=l[r+1]
                sel=min(s1,s2)
                key=1
            else:
                r=l.index(sel)
                sel1=sel
                if(r==0):
                    s1=0
                else:
                    s1=l[r-1]
                if(r==n-1):
                    s2=0
                else:
                    s2=l[r+1]
                sel=max(s1,s2)
                key=0
            k-=1
    else:
        while(1000):
            if(key==0):
                r=l.index(sel)
                sel1=sel
                if(r==0):
                    s1=1000000000
                else:
                    s1=l[r-1]
                if(r==n-1):
                    s2=1000000000
                else:
                    s2=l[r+1]
                sel=min(s1,s2)
                key=1
            else:
                r=l.index(sel)
                sel1=sel
                if(r==0):
                    s1=0
                else:
                    s1=l[r-1]
                if(r==n-1):
                    s2=0
                else:
                    s2=l[r+1]
                sel=max(s1,s2)
                key=0
            k-=1
    k-=1000
    s1=k%2
    if(s1==0):
        print(sel)
    else:
        print(sel1)
    #print(sel)
    t-=1
